const EMPTY_DECK = {
  clubs : {
    0  : null, // two of clubs
    1  : null,
    2  : null,
    3  : null,
    4  : null,
    5  : null,
    6  : null,
    7  : null,
    8  : null,
    9  : null,
    10 : null,
    11 : null,
    12 : null, // ace of clubs
  },
  diamonds : {
    0  : null,
    1  : null,
    2  : null,
    3  : null,
    4  : null,
    5  : null,
    6  : null,
    7  : null,
    8  : null,
    9  : null,
    10 : null,
    11 : null,
    12 : null,
  },
  hearts : {
    0  : null,
    1  : null,
    2  : null,
    3  : null,
    4  : null,
    5  : null,
    6  : null,
    7  : null,
    8  : null,
    9  : null,
    10 : null,
    11 : null,
    12 : null,
  },
  spades : {
    0  : null,
    1  : null,
    2  : null,
    3  : null,
    4  : null,
    5  : null,
    6  : null,
    7  : null,
    8  : null,
    9  : null,
    10 : null,
    11 : null,
    12 : null,
  },
};

module.exports = EMPTY_DECK;
